package universidad.entity;
// Generated 13-ene-2020 20:34:36 by Hibernate Tools 4.3.1



/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private int edad;
     private double beca;

    public Alumno() {
    }

    public Alumno(String dni, String nombre, int edad, double beca) {
       this.dni = dni;
       this.nombre = nombre;
       this.edad = edad;
       this.beca = beca;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public double getBeca() {
        return this.beca;
    }
    
    public void setBeca(double beca) {
        this.beca = beca;
    }




}


