package universidad.entity;
// Generated 13-ene-2020 20:34:36 by Hibernate Tools 4.3.1



/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private String codAsig;
     private String nombre;
     private int ct;
     private int cp;
     private String curso;

    public Asignatura() {
    }

	
    public Asignatura(String codAsig, String nombre, int ct, int cp) {
        this.codAsig = codAsig;
        this.nombre = nombre;
        this.ct = ct;
        this.cp = cp;
    }
    public Asignatura(String codAsig, String nombre, int ct, int cp, String curso) {
       this.codAsig = codAsig;
       this.nombre = nombre;
       this.ct = ct;
       this.cp = cp;
       this.curso = curso;
    }
   
    public String getCodAsig() {
        return this.codAsig;
    }
    
    public void setCodAsig(String codAsig) {
        this.codAsig = codAsig;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCt() {
        return this.ct;
    }
    
    public void setCt(int ct) {
        this.ct = ct;
    }
    public int getCp() {
        return this.cp;
    }
    
    public void setCp(int cp) {
        this.cp = cp;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }




}


