package universidad.entity;
// Generated 13-ene-2020 20:34:36 by Hibernate Tools 4.3.1



/**
 * MatriculaId generated by hbm2java
 */
public class MatriculaId  implements java.io.Serializable {


     private String dni;
     private String codAsig;

    public MatriculaId() {
    }

    public MatriculaId(String dni, String codAsig) {
       this.dni = dni;
       this.codAsig = codAsig;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getCodAsig() {
        return this.codAsig;
    }
    
    public void setCodAsig(String codAsig) {
        this.codAsig = codAsig;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatriculaId) ) return false;
		 MatriculaId castOther = ( MatriculaId ) other; 
         
		 return ( (this.getDni()==castOther.getDni()) || ( this.getDni()!=null && castOther.getDni()!=null && this.getDni().equals(castOther.getDni()) ) )
 && ( (this.getCodAsig()==castOther.getCodAsig()) || ( this.getCodAsig()!=null && castOther.getCodAsig()!=null && this.getCodAsig().equals(castOther.getCodAsig()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDni() == null ? 0 : this.getDni().hashCode() );
         result = 37 * result + ( getCodAsig() == null ? 0 : this.getCodAsig().hashCode() );
         return result;
   }   


}


